name: StructureSpawner
version: '1.0-SNAPSHOT'
main: com.yourdomain.structurespawner.StructureSpawner
api-version: '1.21'
author: Been # Hoặc tên của bạn
description: Tự động spawn các công trình từ file .schem trong các chunk mới.
depend: [WorldEdit]

commands:
  structurespawner:
    description: Lệnh chính của plugin StructureSpawner.
    aliases: [ss, congtrinh]
    permission: structurespawner.admin
    usage: "/<command> [reload|list]"

permissions:
  structurespawner.admin:
    description: Cho phép sử dụng tất cả các lệnh của StructureSpawner.
    default: op