name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout
        uses: actions/checkout@v4 # Cập nhật từ v3 lên v4

      # Step 2: Cài đặt Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Cập nhật từ v3 lên v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache các thư viện Maven để build nhanh hơn
      # Đây là lỗi chính: GitHub yêu cầu sử dụng v4
      - name: Cache Maven packages
        uses: actions/cache@v4 # <<<< ĐÃ SỬA: Cập nhật từ v2 lên v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Step 4: Build plugin bằng Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Tải lên file .jar đã build
      # Đây là lỗi thứ hai: GitHub yêu cầu sử dụng v4
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # <<<< ĐÃ SỬA: Cập nhật từ v3 lên v4
        with:
          name: StructureSpawner-Plugin
          path: target/StructureSpawner-*.jar